FROM python:3.11-slim-bookworm

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PORT=5000

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY 07_build_app/ ./07_build_app/
COPY 01_dataset/ ./01_dataset/
COPY 07_build_app/ ./07_build_app/
WORKDIR /app/07_build_app

EXPOSE 5000

CMD ["uvicorn", "ingestion_api:app", "--host", "0.0.0.0", "--port", "5000"]